# **Lab 6**

**(1) Demonstrate the following Numpy functions:**

*     (a)Arithmetic functions: 

In [32]:
# Importing Numpy as np
import numpy as np

# Creatting 2 arrays of shape (4,4)

arr1 = np.arange(5,81,5).reshape(4,4)
print("arr1 = \n", arr1)

print()

arr2 = np.arange(2,18).reshape(4,4)
print("arr2 = \n",arr2)

arr1 = 
 [[ 5 10 15 20]
 [25 30 35 40]
 [45 50 55 60]
 [65 70 75 80]]

arr2 = 
 [[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]]


In [33]:
# add()
""" numpy.add()- performs element-wise addition between
two arrays """

print("Addition of arr1 and arr2 is : \n")
np.add(arr1,arr2)

Addition of arr1 and arr2 is : 



array([[ 7, 13, 19, 25],
       [31, 37, 43, 49],
       [55, 61, 67, 73],
       [79, 85, 91, 97]])

In [34]:
# Subtract()
"""We use this function to output the difference of two arrays. If we subtract
 two arrays having dissimilar shapes we get “Value Error”. """

print("Subtraction of arr2 from arr1 is : \n")
np.subtract(arr1,arr2)

Subtraction of arr2 from arr1 is : 



array([[ 3,  7, 11, 15],
       [19, 23, 27, 31],
       [35, 39, 43, 47],
       [51, 55, 59, 63]])

In [35]:
# Multiply()
""" We use this function to output the multiplication of two arrays.
 We cannot work with dissimilar arrays. """

print("Multiplication of arr1 and arr2 is : \n")
np.multiply(arr1,arr2)

Multiplication of arr1 and arr2 is : 



array([[  10,   30,   60,  100],
       [ 150,  210,  280,  360],
       [ 450,  550,  660,  780],
       [ 910, 1050, 1200, 1360]])

In [36]:
# Divide()
"""" We use this function to output the division of two arrays.
 We cannot divide dissimilar arrays. """

print("Division of arr1 by arr2 is : \n")
np.divide(arr1,arr2) 

Division of arr1 by arr2 is : 



array([[2.5       , 3.33333333, 3.75      , 4.        ],
       [4.16666667, 4.28571429, 4.375     , 4.44444444],
       [4.5       , 4.54545455, 4.58333333, 4.61538462],
       [4.64285714, 4.66666667, 4.6875    , 4.70588235]])

In [37]:
# Floor Divide()
""" Round a number to the nearest integer toward minus infinity. """
print("Rounding the Division of arr1 by arr2 to the nearest " 
      "integer toward minus infinity : \n")
np.floor_divide(arr1,arr2)

Rounding the Division of arr1 by arr2 to the nearest integer toward minus infinity : 



array([[2, 3, 3, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

*   (b) Aggregate functions:

In [38]:
# Creating a random array of shape (10,6)

arr_big = np.random.random((10,6))
print(arr_big)

[[0.6740902  0.35007379 0.47971371 0.25557308 0.26857771 0.74702833]
 [0.48779257 0.95499393 0.85683713 0.8671896  0.33554499 0.85829978]
 [0.2491362  0.50964969 0.59590154 0.03209415 0.28276064 0.94201058]
 [0.00525947 0.93265488 0.02893176 0.66000545 0.10120775 0.33201818]
 [0.31815686 0.72097641 0.42579924 0.48980465 0.95721091 0.41274789]
 [0.92961985 0.95810356 0.56971089 0.66443746 0.44539983 0.45624281]
 [0.85569798 0.2223138  0.35784128 0.75176509 0.33206621 0.46042646]
 [0.29773525 0.14531889 0.90704735 0.51292948 0.41193785 0.91196287]
 [0.87499528 0.79396776 0.49897105 0.02223547 0.89734131 0.78917935]
 [0.06749556 0.38578299 0.59636399 0.19425551 0.79492835 0.04897435]]


In [39]:
# Min()
print("Minimum Value in arr_big is : ", np.min(arr_big))

# Max
print("Maximum Value in arr_big is : ", np.max(arr_big))

print()

# Mean
print("Mean Value in arr_big is    : ", np.mean(arr_big))

# Median
print("Median Value in arr_big is  : ", np.median(arr_big))


Minimum Value in arr_big is :  0.0052594717074475605
Maximum Value in arr_big is :  0.9581035625137124

Mean Value in arr_big is    :  0.5214514829513219
Median Value in arr_big is  :  0.48879861118300133


In [40]:
# Std()
print("Standard Deviation in arr_big is : ", np.std(arr_big))

# Var()
print("Variance in arr_big is           : ", np.max(arr_big))

Standard Deviation in arr_big is :  0.29090676221972256
Variance in arr_big is           :  0.9581035625137124


In [41]:
# Percentile()
print("\n Rank-based statistics of elements in arr_big ")
print("rank-based statistics of elements [25] : ", np.percentile(arr_big, 25))
print("rank-based statistics of elements [75] : ", np.percentile(arr_big, 75))


 Rank-based statistics of elements in arr_big 
rank-based statistics of elements [25] :  0.31305145963653647
rank-based statistics of elements [75] :  0.7942079056908145


In [42]:
# Any()
# Evaluate whether any elements are true

print("Evaluating any element in arr_big is greaterthan 0.5")
np.any(arr_big>.5)

Evaluating any element in arr_big is greaterthan 0.5


True

In [43]:
# All()
# Evaluate whether all elements are true

print("Evaluating all element in arr_big are greaterthan 0.5")
np.all(arr_big>.5)

Evaluating all element in arr_big are greaterthan 0.5


False

**(2) Demonstrate the Numpy Broadcasting Rules with examples of your choice**

What is Broadcasting?
* Broadcasting is simply a set of rules for applying binary universal function(addition, subtraction, multiplication, etc.) on arrays of different sizes.

# Rules of Broadcasting
Broadcasting in NumPy follows a strict set of rules to determine the interaction
between the two arrays:
* Rule 1: If the two arrays differ in their number of dimensions, the shape of 
the one with fewer dimensions is padded with ones on its leading (left) side.
* Rule 2: If the shape of the two arrays does not match in any dimension, the   array with shape equal to 1 in that dimension is stretched to match the other shape.
* Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

Example 1

In [44]:
# Creating 2 arrays of 2D and 1D

A = np.ones((2,3))  # 2D
a = np.arange(1,4)  # 1D

print("The 2D array, A :\n", A)
print()
print("The 1D array, a :\n", a)

The 2D array, A :
 [[1. 1. 1.]
 [1. 1. 1.]]

The 1D array, a :
 [1 2 3]


In [45]:
# Finding the shape of 2 arrays

print(A.shape)
print(a.shape)

(2, 3)
(3,)


1.  By rule 1, the array 'a' has fewer dimensions, so pad it on the left with ones, and shape become:
*  A.shape -> (2, 3)
*  a.shape -> (1, 3)
2.  By rule 2, the first dimension disagrees, so stretch this dimension to:

*  A.shape -> (2, 3)
*  a.shape -> (2, 3)

In [46]:
# Adding the 2 arrays
print("Adding : A(2D) + a(1D)")
print()
print(A, " + ", a)
print()

A+a

Adding : A(2D) + a(1D)

[[1. 1. 1.]
 [1. 1. 1.]]  +  [1 2 3]



array([[2., 3., 4.],
       [2., 3., 4.]])

Example 2

In [47]:
B = np.arange(3,6).reshape((3, 1))
b = np.arange(3)

print("B = \n", B)
print()
print("b = \n", b)

B = 
 [[3]
 [4]
 [5]]

b = 
 [0 1 2]


In [48]:
print("Shape of B is : ", B.shape)
print("Shape of b is : ", b.shape)

Shape of B is :  (3, 1)
Shape of b is :  (3,)


1.  Rule 1 says we must pad the shape of b with ones:
* B.shape -> (3, 1)
* b.shape -> (1, 3)
2.  Rule 2 tells us that we upgrade each of these ones to match the corresponding
size of the other array:
* B.shape -> (3, 3)
* b.shape -> (3, 3)


> Now the Shapes are compatible



In [49]:
# Adding the 2 arrays

print("Adding : B + b")
print()
print(B, " + ", b)
print()
B + b

Adding : B + b

[[3]
 [4]
 [5]]  +  [0 1 2]



array([[3, 4, 5],
       [4, 5, 6],
       [5, 6, 7]])

Example 3

In [50]:
C = np.ones((3, 2))
c = np.arange(3)

print("C = \n", C)
print()
print("c = \n", c)

C = 
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

c = 
 [0 1 2]


In [51]:
print("Shape of C is : ", C.shape)
print("Shape of c is : ", c.shape)

Shape of C is :  (3, 2)
Shape of c is :  (3,)


The shapes of the arrays are:
* C.shape = (3, 2)
* c.shape = (3,)
1.  Rule 1 tells us that we must pad the shape of a with ones:
*  C.shape -> (3, 2)
*  c.shape -> (1, 3)
2.  Rule 2, the first dimension of a is stretched to match that of M:
*  C.shape -> (3, 2)
*  c.shape -> (3, 3)
3.  Rule 3 — the final shapes do not match, so these two arrays are incompatible

In [52]:
# Adding the 2 arrays

print("Adding : C + c")
print()
print(C, " + ", c)
print()
C + c

Adding : C + c

[[1. 1.]
 [1. 1.]
 [1. 1.]]  +  [0 1 2]



ValueError: ignored

In above case error occured. The error is:
* ValueError: operands could not be broadcast together with shapes (3,2) (3,)





