 **Lab Exercise-5**

---



(a) **Array Creation** 

In [ ]:
# Importing Numpy
import numpy as np          

In [ ]:
""" array() - Ordered collection of elements of basic data
types of given length """

a = np.array([10,20,30,40,50,60,70,80,90,100])
print(a)

[ 10  20  30  40  50  60  70  80  90 100]


In [ ]:
""" arrange() - returns equally spaced numbers with in the 
given range based on step size """

b = np.arange(10,101,10)
print(b)

[ 10  20  30  40  50  60  70  80  90 100]


In [ ]:
""" Zeros - returns an array of given shape and type
filled with zeros """

c = np.zeros((4,5))
print(c)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
""" Ones - returns an array of given shape and type filled
with ones """

d = np.ones((4,5))
print(d)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
""" full() - Create a constant array """

e = np.full(4,5)
print(e)


[5 5 5 5]


In [ ]:
""" eye() - Create an identity matrix """

f = np.eye(4,5)
print(f)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [ ]:
""" random() - Create an array with random values """

g = np.random.random((4,2))
print(g)

[[0.81515474 0.02415527]
 [0.84761976 0.34513453]
 [0.02626231 0.1336901 ]
 [0.38880663 0.17615676]]


In [ ]:
""" linspace - returns equally spaced numbers within the
given range based on the sample number """

h = np.linspace(10,100,10)
print(h)

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


(b) **Attributes of arrays**


In [ ]:
a = np.ones((4,5))
print(d)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
a.size     # Number of array elements

20

In [ ]:
a.shape    # Array dimensions

(4, 5)

In [ ]:
a.ndim     # Number of array dimensions

2

In [ ]:
a.dtype    # Data type of array elements

dtype('float64')

In [ ]:
a.itemsize   # Length of one array element in bytes

8

In [ ]:
a.data       # Python buffer object pointing to the start of the array's data

(c) **Indexing of arrays**

In [ ]:
# Getting and setting the value of individual array elements
# Select the element using index numbers

a = np.array([10,20,30,40,50,60,70,80,90,100])
b = np.array([11,22,33,44,55,66,77,88,99,100])

print(" The 2nd Element from a is : ", a[1])
print(" The 4th Element from b is : ", b[3])

 The 2nd Element from a is :  20
 The 4th Element from b is :  44


In [ ]:
# Select the element using index numbers

c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]])
c[1,0,1]  

2.0

(d) **Slicing of arrays**

In [ ]:
# Getting and setting smaller subarrays within a larger array

c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]])
c[0:2,1]

array([[4., 5., 6.],
       [4., 5., 6.]])

In [ ]:
c = np.array([(1.5,2,3), (4,5,6)])
c[1:2]

array([[4., 5., 6.]])

In [ ]:
c = np.array([(1.5,2,3), (4,5,6)])
c[1:2,0]

array([4.])

(e)**Reshaping of arrays**

In [ ]:
""" reshape() - Changing the shape of a given array, but don’t change data """

a = np.ones((4,5))
a.reshape(2,10)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
b = np.ones((3,4))
b.reshape(6,2)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])